server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    #  第二:通过属于文件或者yml文件配置
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com:80/
          predicates:
            - Path=/du
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
